<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '31f78ff57bd21f8998b3a90604abd111',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'DATABASE_URL' => 'mysql://e1875009_TP_4D6:cO1oGb3Y61L@techinfo-cstj.ca:3306/e1875009_TP_4D6_H23',
  'MAILER_DSN' => 'null://null',
  'STRIPE_KEY' => 'sk_test_51MtziNAqxQVqeKTB0oSL6npuRVSWaqLzl2ingASvZMoip0OCH6AKL4SiBKAeCtopdym6LUnMKIuahV2Xt83lzir300AUvR9Vbw'
);
