<?php

namespace ContainerSsUpuoo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PFg8NgkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PFg8Ngk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PFg8Ngk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::adminAddProduct' => ['privates', '.service_locator.xJpW8Z9', 'get_ServiceLocator_XJpW8Z9Service', true],
            'App\\Controller\\AdminController::adminModifyProduct' => ['privates', '.service_locator.xJpW8Z9', 'get_ServiceLocator_XJpW8Z9Service', true],
            'App\\Controller\\ProfileController::login' => ['privates', '.service_locator.KEykpDM', 'get_ServiceLocator_KEykpDMService', true],
            'App\\Controller\\ProfileController::profile' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.gxu4pR9', 'get_ServiceLocator_Gxu4pR9Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:adminAddProduct' => ['privates', '.service_locator.xJpW8Z9', 'get_ServiceLocator_XJpW8Z9Service', true],
            'App\\Controller\\AdminController:adminModifyProduct' => ['privates', '.service_locator.xJpW8Z9', 'get_ServiceLocator_XJpW8Z9Service', true],
            'App\\Controller\\ProfileController:login' => ['privates', '.service_locator.KEykpDM', 'get_ServiceLocator_KEykpDMService', true],
            'App\\Controller\\ProfileController:profile' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.gxu4pR9', 'get_ServiceLocator_Gxu4pR9Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::adminAddProduct' => '?',
            'App\\Controller\\AdminController::adminModifyProduct' => '?',
            'App\\Controller\\ProfileController::login' => '?',
            'App\\Controller\\ProfileController::profile' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:adminAddProduct' => '?',
            'App\\Controller\\AdminController:adminModifyProduct' => '?',
            'App\\Controller\\ProfileController:login' => '?',
            'App\\Controller\\ProfileController:profile' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
