<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLCTfYoy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLCTfYoy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLCTfYoy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLCTfYoy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLCTfYoy\App_KernelDevDebugContainer([
    'container.build_hash' => 'LCTfYoy',
    'container.build_id' => 'c8015521',
    'container.build_time' => 1684691158,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLCTfYoy');
